name: pythonscripts
channels:
  - conda-forge
  - defaults
dependencies:
  - spyder 
  - rasterio
  - pandas
  - openpyxl
  - geopandas
  - numpy
  - matplotlib
  - scipy
  - xlrd
  - regex
  - flask
  - ffmpeg
  - pip
  - pip:
    - openai-whisper
    